#Use with docker compose -f docker-compose.yml -f docker-compose.prerender.yml up

services:
  map:
    volumes:
      - ./cfg/postgresql.prerender.conf.tmpl:/etc/postgresql/current/main/postgresql.custom.conf.tmpl
      - ./scripts/render_list_geo.pl:/usr/bin/render_list_geo
    environment:
      - RENDER_THREADS=4
      - FLAT_NODES=enabled
      # However you may change the memory usage (-C)
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      # Use this variant on slow disks or less RAM:
      # - OSM2PGSQL_EXTRA_ARGS=-C 1024 --disable-parallel-indexing
    shm_size: '16g'
